using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.IdentityModel.Tokens;
using System.IdentityModel.Tokens.Jwt;
using Microsoft.IdentityModel.Tokens;

namespace OAuth2POC
{
    public partial class _Default : Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            // get the JWT token string from Authorization header
            // This would be sent from Canvas (Consumer) to LTI Tool (Provider) and signed
            // Here will make one up
            
            
            //SigningCredentials signingCredentials = new SigningCredentials(SecurityKey, SecurityAlgorithms.HmacSha256);
            //JwtHeader header = new JwtHeader()
            //JwtSecurityToken token = new JwtSecurityToken()

            //string authHeader;
            //authHeader = Request.Form["Authorization"] ?? testAuthHeader;

            //string jwtTokenString = authHeader.Substring(authHeader.IndexOf(' '));

            //JwtSecurityToken jwtToken = new JwtSecurityToken(jwtTokenString);

            // check validity of the token to make sure it has not been tampered with

        }

        private const string testToken = "eyJhbGciOiJSUzI1NiIsImtpZCI6IlZhNWFpcUtlWHZBMTlaRTlTYjl3clJVcVEwbHpnRFVCN2wyWjM1RVR3Yk0ifQ.eyJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS9jbGFpbS9tZXNzYWdlX3R5cGUiOiJMdGlSZXNvdXJjZUxpbmtSZXF1ZXN0IiwiZ2l2ZW5fbmFtZSI6Ik5vYmxlIiwiZmFtaWx5X25hbWUiOiJNRCIsIm1pZGRsZV9uYW1lIjoiSGF5bGV5IiwicGljdHVyZSI6Imh0dHA6Ly9leGFtcGxlLm9yZy9Ob2JsZS5qcGciLCJlbWFpbCI6Ik5vYmxlLk1EQGV4YW1wbGUub3JnIiwibmFtZSI6Ik5vYmxlIEhheWxleSBNYXJ2aW4gTUQiLCJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS9jbGFpbS9yb2xlcyI6WyJodHRwOi8vcHVybC5pbXNnbG9iYWwub3JnL3ZvY2FiL2xpcy92Mi9pbnN0aXR1dGlvbi9wZXJzb24jU3R1ZGVudCIsImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjTGVhcm5lciIsImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL21lbWJlcnNoaXAjTWVudG9yIl0sImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL3JvbGVfc2NvcGVfbWVudG9yIjpbImh0dHA6Ly9wdXJsLmltc2dsb2JhbC5vcmcvdm9jYWIvbGlzL3YyL2luc3RpdHV0aW9uL3BlcnNvbiNBZG1pbmlzdHJhdG9yIl0sImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL3Jlc291cmNlX2xpbmsiOnsiaWQiOiI3MCIsInRpdGxlIjoiQSB0aXRsZSIsImRlc2NyaXB0aW9uIjpudWxsfSwiaHR0cHM6Ly9wdXJsLmltc2dsb2JhbC5vcmcvc3BlYy9sdGkvY2xhaW0vY29udGV4dCI6eyJpZCI6IjI1IiwibGFiZWwiOiJlbmdfMTAxIiwidGl0bGUiOiJFbmcgMTAxIiwidHlwZSI6WyJDb3Vyc2VPZmZlcmluZyJdfSwiaHR0cHM6Ly9wdXJsLmltc2dsb2JhbC5vcmcvc3BlYy9sdGkvY2xhaW0vdG9vbF9wbGF0Zm9ybSI6eyJuYW1lIjoiSmFtZXMgVGVzdCBQbGF0Zm9ybSIsImNvbnRhY3RfZW1haWwiOiIiLCJkZXNjcmlwdGlvbiI6IiIsInVybCI6IiIsInByb2R1Y3RfZmFtaWx5X2NvZGUiOiIiLCJ2ZXJzaW9uIjoiMS4wIn0sImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpLWFncy9jbGFpbS9lbmRwb2ludCI6eyJzY29wZSI6WyJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS1hZ3Mvc2NvcGUvbGluZWl0ZW0iLCJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS1hZ3Mvc2NvcGUvcmVzdWx0LnJlYWRvbmx5IiwiaHR0cHM6Ly9wdXJsLmltc2dsb2JhbC5vcmcvc3BlYy9sdGktYWdzL3Njb3BlL3Njb3JlIl0sImxpbmVpdGVtcyI6Imh0dHBzOi8vbHRpLXJpLmltc2dsb2JhbC5vcmcvcGxhdGZvcm1zLzI3L2NvbnRleHRzLzI1L2xpbmVfaXRlbXMifSwiaHR0cHM6Ly9wdXJsLmltc2dsb2JhbC5vcmcvc3BlYy9sdGktbnJwcy9jbGFpbS9uYW1lc3JvbGVzZXJ2aWNlIjp7ImNvbnRleHRfbWVtYmVyc2hpcHNfdXJsIjoiaHR0cHM6Ly9sdGktcmkuaW1zZ2xvYmFsLm9yZy9wbGF0Zm9ybXMvMjcvY29udGV4dHMvMjUvbWVtYmVyc2hpcHMuanNvbiIsInNlcnZpY2VfdmVyc2lvbiI6IjIuMCJ9LCJpc3MiOiJodHRwczovL2x0aS1yaS5pbXNnbG9iYWwub3JnIiwiYXVkIjoiMTIzIiwiaWF0IjoxNTMzNzQzOTg1LCJleHAiOjE1MzM3NDQyODUsInN1YiI6ImViN2Q4N2RhZmRiZjRkMzcxMGQwIiwibm9uY2UiOiIyYzZmMWE0YjMzZTNlNDVmNmUxZSIsImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL3ZlcnNpb24iOiIxLjMuMCIsImxvY2FsZSI6ImVuLVVTIiwiaHR0cHM6Ly9wdXJsLmltc2dsb2JhbC5vcmcvc3BlYy9sdGkvY2xhaW0vbGF1bmNoX3ByZXNlbnRhdGlvbiI6eyJkb2N1bWVudF90YXJnZXQiOiJpZnJhbWUiLCJoZWlnaHQiOjMyMCwid2lkdGgiOjI0MCwicmV0dXJuX3VybCI6Imh0dHBzOi8vbHRpLXJpLmltc2dsb2JhbC5vcmcvcGxhdGZvcm1zLzI3L3JldHVybnMifSwiaHR0cHM6Ly93d3cuZXhhbXBsZS5jb20vZXh0ZW5zaW9uIjp7ImNvbG9yIjoidmlvbGV0In0sImh0dHBzOi8vcHVybC5pbXNnbG9iYWwub3JnL3NwZWMvbHRpL2NsYWltL2N1c3RvbSI6eyJteUN1c3RvbVZhbHVlIjoxMjN9LCJodHRwczovL3B1cmwuaW1zZ2xvYmFsLm9yZy9zcGVjL2x0aS9jbGFpbS9kZXBsb3ltZW50X2lkIjoiMTIzIn0.CnPQFkE5hxxlA3HzEaKG6qXf_Q9KEkbJEA1Xi-eiUaq8KHKCOyWQn35Yzp-JP12UUCaNtRbz5Y1aLIIpMekco-cgQ4EDs5-kW5hrobpqO-HOwfouszi4SXBczCh181FJLXzFijPQBnfcN6s-veRsT0yD-xjWGzdoftNgQhQJ9fHS5DPhrAYjya4aExbbYz25xcWCpjR_05qzfwjU8cCqDqTEHKFRg5SiTJG2NnrvGG3ukVmPcGJPtdNX85WPHr6-DV4MUGNYVXbIxMCUBEEhhyXcPDJMqvfIJ-vn19QLK_Svw57FedQxq0Ku0jiu2CR29abynyGTXExFuygM16oDfw";
        private string testAuthHeader = $"Bearer {testToken}";

        private const string toolPublicKey = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsGW9g5La/lm3YuKUSet5 VaWlr8j53MDwDZ5XpyJpv1BohfIHX7qJn1KzO3LMJXIL+K/WfHE+MJCpcAJvzxil iBJmEb2uD9EVIwHVKik6CZ7UuxzGySxhtRRNDUiG8akjTnr6mQbikrRTYTdwGcXj L3RSV7bOy2sbcqBebiXSxt81MMmMYIH6PyctheD3ZWRbo22F0CaiRygfFvirn7rx Gz2GtufR0rHxCqGFQ5eZV4gKUE/KAJlCi/XTrm/BYmBLWO1o2cjWUdqtI3N68h2a t/zSfBozsazAFXjxZHmESaMGGlDF4rqw9EnxOuZp+kc6HMg/or+p4ExPUPpVnlAR XwIDAQAB";
    }
}